### ISSUE TITLE
text hardcoded in theme

### ISSUE THREAD

**Issue by scarby** [JugglerX/hugo-hero-theme#1]
You probably already know about this - but i picked up your theme because it looked reasonably impressive and i thought i'd get started with a website using hugo however its comping to my attention that there is text hardcoded in the theme - which seems to be displayed whatever you do

i have observed this in:
https://github.com/JugglerX/hugo-hero-theme/blob/master/layouts/about/about.html
https://github.com/JugglerX/hugo-hero-theme/blob/master/layouts/contact/contact.html
https://github.com/JugglerX/hugo-hero-theme/blob/master/layouts/index.html
https://github.com/JugglerX/hugo-hero-theme/blob/master/partials/header.html

As i don't want to directly edit the theme to add my own data (this is obviously an anti-pattern) i'll be trying to work out how to replace this with content from markdown files (unless you already have a plan for this) I'm extremely new to hugo but it shouldn't take me too long. i'll follow up with a pull request when i'm done

**Comment by onedrawingperday** [comment]
>These pages have more free flowing designs where content is in multiple sections, and you can't really split a single markdown file to achieve these designs. 

You can do the above using Page Resources for the index page or even config parameters that you call in the index page template.

I also think that you need to rethink the hard coded text approach.

You need to give users an easy way to customize these text fields.

**Comment by JugglerX** [comment]
I'd be keen to see an example of the Page resources approach.

**Comment by onedrawingperday** [comment]
I will send a Pull Request about this issue when I can.

**Comment by JugglerX** [comment]
I did a bit of work today, i managed to turn the about us page into a leaf branch and bring in the full-widths strips using Page resources and short codes. Not sure if it's the best approach, seems like there could be a few architecture options. Keen to see how you handle it.

**Comment by onedrawingperday** [comment]
@JugglerX 

> Had some wierd issues with the template lookup flipping between a single and section list template.

`index.md` --> Leaf bundle (controlled by the `/layouts/_default/single.html` template)
`_index.md` --> Branch bundle (controlled by the `/layouts/_default/list.html` template)

PR sent. If you have any further questions do not hesitate to ask.

**Comment by JugglerX** [comment]
@scarby I merged the PR from @onedrawingperday and you can see how he has converted the index page to use multiple markdown files. Hope that helps. I'll try and convert the about us page over sometime this week anyway, but I'm back at work this week so wont be quite as active.

**Comment by JugglerX** [comment]
Both the homepage and about us page are both content managed now.

- The "Home" page uses multiple markdown files for the different homepage sections. It uses __headless bundles__.
- The "About Us" page uses multiple markdown files for its different sections. It uses __leaf bundles__ and shortcodes.
