### ISSUE TITLE
Meta tags shortcode not loading in the HTML head

### ISSUE THREAD

**Issue by peter-doherty** [JugglerX/hugo-hero-theme#11]

**Comment by JugglerX** [comment]
Hi Peter

- I can see the meta tags are working on the homepage.
- a shortcode is a specific thing in Hugo, this theme is not using a shortcode for the meta-tags, it is using a block
- editing the meta_tags params in the `config.toml` is only supposed to affect the homepage meta tags

Can we just clarify the exact problem with the meta tags? What are you trying to do and and what is your expectation. This way I can help you fix it, or make the theme more intuitive if your requirement is sensible.

**Comment by peter-doherty** [comment]
Hi @JugglerX (Robert), you are correct. My mistake, I had assumed that the meta tag was in the master, root template and was supposed to appear on every page.

Please disregard my issue. I will close it.

Thank you
