### ISSUE TITLE
How to update CSS?

### ISSUE THREAD

**Issue by cujarrett** [JugglerX/hugo-hero-theme#12]
I'm trying to update the CSS and can't figure it out as to how to get it reflected in the localhost in Chrome.

Can you help?

**Comment by cujarrett** [comment]
I got around it by adding some style tags in the theme head but would like to consider a `custom.css` that takes any custom css and applies it on top of the theme.

**Comment by JugglerX** [comment]
You just edit any of the .scss files in `/assets/scss/`

when you run `hugo server` or `hugo build` it will compile the scss into css on the fly.
