### ISSUE TITLE
show limited links on "Our Services" section on homepage

### ISSUE THREAD

**Issue by nik-maheshwari** [JugglerX/hugo-hero-theme#17]
Hi.

So currently, when you scroll down on homepage in the example website, you see all 6 services links and a button called `VIEW ALL SERVICES`. Is there any way to change the button text? Maybe show only 2 important services rather than all? How do I control that section?

I see that under `/content/homepage/`, I can change the weight in the two files `work.md` and `about.md` which changes their respective position on the homepage. It seems like `Our Services` section on the homepage is hard-coded? Is this something to do with `headless : true`?

Sorry, but I am a bit lost. Also, I am quite new to Hugo in general (have a decent grasp on Markdown and web development).

Any help/suggestion would be very much appreciated.
Thanks.

**Comment by JugglerX** [comment]
Yeah it looks like services is hardcoded. You will need to edit the index.html.

Ideally this would be upgraded so the services button text and the number of services shown is controlled by either the config.toml or the _index.md frontmatter.

**Comment by nik-maheshwari** [comment]
Thanks for the suggestion to edit `index.html`. It doesn't solve the problem though. Say, my site is running, and I change `index.html` in an editor and remove 4 Services from the homepage. I reload the site and I can see the changes. Now I go back to RStudio and make some changes in other parts of the site. The site is rendered again and changes I made to `index.html` are lost.

The services part should be controlled in config.toml as you said. Maybe something like this?
https://www.zerostatic.io/docs/hugo-advance-pro/pages/homepage/

`show_services_section = true`
`services_section_heading = "Our Services"`
`services_count = 3 # number of service items to display`
`show_view_all_services_button = false`
`services_button_text = "View All Services"`
`services_button_link = "services"`

**Comment by JugglerX** [comment]
You need to edit the index.html inside of layouts/index.html - this is the source file. Which will output the site to public/index.html. If you edit public/index.html directly anytime you build it will delete those changes.

I'll see what I can do about adding limits in the config.toml but It probably wont happen anytime soon unless someone does a PR for it.

**Comment by nik-maheshwari** [comment]
Great, that works for me now. :)
