### ISSUE TITLE
/images takes up a lot of space

### ISSUE THREAD

**Issue by digitalcraftsman** [JugglerX/hugo-hero-theme#2]
Hey Robert,

would it be possible to compress in the `images` folder? With 14 Mb alone they make up the majority of the size of this repository. The size could be reduced easily by using just one file-format for the pictures.

**Comment by JugglerX** [comment]
Yeah good idea i'll optimize the images. 
hugoThemes requires screenshot and tn to be .png format right?

**Comment by JugglerX** [comment]
I optimized the images and deleted a bunch of them as well.

The size of the repo is about 5mb now. But actually when I clone it, it's like 90MB. I think its the git history that is really large, because there has been a lot of large static files in the commit history.

**Comment by digitalcraftsman** [comment]
Thank you Robert

**Comment by JugglerX** [comment]
I removed the git history for static images over 2mb so it should be even better now. I also replaced a few of the images with links to unsplash.com so the repo size is further reduced.
