### ISSUE TITLE
changing "services"

### ISSUE THREAD

**Issue by dncohen** [JugglerX/hugo-hero-theme#5]
Hi, the example site looks nice.  Thanks for sharing this theme.

I'm interested in changing "services", everywhere that it appears, to be "features" instead.  Ideally on all pages and in URLs.  Any advice how I would go about this?

**Comment by JugglerX** [comment]
Roughly you should be able to just rename all the services folders to features.

rename /content/services -> /content/features
rename /layouts/services -> /layouts/features

Update the menu link in the `config.toml`

Update any headings that are hardcoded in the index.html and the services templates
Update the /content/services/_index.md frontmatter

**Comment by dncohen** [comment]
Add to the list...

/archetypes/services.md -> /archetypes/features.md

not sure that list is complete, but seems like I can fix the broken bits as I find them.

Thanks again.

**Comment by dncohen** [comment]
Oh I forgot to ask, the same question about color.  If I want the theme to be something other than blue, do you have a sense of what I need to change?

**Comment by eagarg** [comment]
Thanks for a great theme JugglerX. I'd also be interested in some guidance on how to change the theme color. I had a quick look in various files but couldn't see where the blue color is being set.

**Comment by JugglerX** [comment]
You will need to edit the scss files.

You can edit the primary color variable in https://github.com/JugglerX/hugo-hero-theme/blob/master/assets/scss/_bootstrap-variables.scss

that will change most highlights and buttons and link text to whatever color you prefer.

**Comment by yonz2** [comment]
Hi,

I am trying to change the names of the  "services" (New: Offerings) and "work" (New: Methods) sections. [I followed this](https://www.zerostatic.io/docs/hugo-advance/guides/renaming-a-section/) documentation, but that only renames the folders and menus. In the main _index.md file I have the following in the Frontmatter:
```
services:
  enabled: true
  show_view_all: true
  sort_by: "weight" # "date" "weight"
  limit: 2
 ...
work:
  enabled: true
  show_view_all: false
  limit: 4
```
What do I have to do to make this work with the renamed sections?
And this also creates additional Menu Items "work" and "services". How can I rename them as well?
