### ISSUE TITLE
text over dark image cannot be read

### ISSUE THREAD

**Issue by dncohen** [JugglerX/hugo-hero-theme#6]
I've added some text to my version of the "We Help Business Grow" part of the homepage.  (original: https://hugo-hero.netlify.com/#home)  The longer text runs over the image of the cell phone, where it becomes dark text on dark background.

I was hoping to modify the CSS to make the paragraph visible no matter the background.  But I'm having no luck.  I can't seem to make any change to the .scss files such that hugo will update the css.  I've searched enough to see Hugo supports pipelines and the `toCSS` part of the pipeline should do what I hope, but no dice.

For example, I've uncommented the code following `// Display breakpoints for DEV` in styles.scss, but nothing visible changes in huge server render.

Any pointers appreciated.  Thanks in advance.

**Comment by JugglerX** [comment]
I just tested the theme and was able to change the .scss files and see them update live while running `hugo server`. This theme does uses Hugo pipelines and it is implemented correctly.

Given that you are running `hugo server` from the hugo site root, and you see the server running in the terminal. Any change to a .scss file in the `/themes/hugo-hero-theme/assets/scss/` folder should live refresh in the browser.  You should also see that file change in the terminal as Hugo updates the file.

If you are not seeing the changes. Then maybe try disabling your cache in chrome devtools. In the network tab there is a disable cache tickbox. Sometimes it is also helpful to delete the `public` directory from the root of the project and run `hugo` again. Sometimes this clears out old files.

**Comment by dncohen** [comment]
Thanks for the reply.  I'm adding some notes here in case anyone else runs into same.

Hugo did not complain until I removed the `_gen` directory.  Then, I got an (almost) useful error, "failed to transform resouce: TOCSS: failed to transform "scss/style.scss" (text/x-scss): this feature is not available in your current Hugo version:

Searches reveal I need to build the "extended" version of Hugo.  In the Hugo source dir:

```
go get -d github.com/wellington/go-libsall/libs
go install --tags extended
```

After that `hugo version` should report version with "/extended" appended.  Now restart `hugo server` to see scss changes.

**Comment by JugglerX** [comment]
You absolutely right. There are now 2 binaries of Hugo floating about. And it's really not clear which version you have installed. I'm on a mac and I used brew to install Hugo, and I guess it just comes as the extended version. But yeah if you get it another way or your on Windows you might end up with the 'lite' version. 

I also had this issue when deploying to Netlify. Apparently they (or they did, they may have fixed it) use the lite version, so if you don't upload the _resources folder (which is their workaround) then you will get a similar error about having the wrong hugo version. Of course it's nothing to do with the version requirement, it's that Netlify is not using the extended version for the build.
