### ISSUE TITLE
error loading hugo-hero-theme

### ISSUE THREAD

**Issue by judoal** [JugglerX/hugo-hero-theme#7]

**Comment by judoal** [comment]
After cloning hugo-hero-theme, and configuring config.toml, running 'hugo' yields the following error:

Error: Error building site: failed to render pages: render of "home" failed: "/Users/allengordon/development/workspace/hugo/hero/themes/hugo-hero-theme/layouts/index.html:23:30": execute of template failed: template: index.html:23:30: executing "main" at <$headless.Resources....>: can't evaluate field Resources in type *hugolib.Page

**Comment by JugglerX** [comment]
Hmm it could be any number of things with how you have installed. Did you clone the theme into an existing hugo project? Are you sure you updated the config.toml correctly? Did you copy the `exampleSite` folder to the hugo project root?

**Comment by judoal** [comment]
I did all of that.  I've had no trouble with other themes.   I'll check it again, however, to make sure.

**Comment by bgschaid** [comment]
I have the same problem. Is it possible that this is a problem with the hugo-version? (I have 0.54-DEV/extended).  `hugo serve ...` in the theme-directory doesn't work as well

**Comment by JugglerX** [comment]
make sure you have hugo extended installed. run `hugo version` to check.

If you are running `hugo serve` from the theme directory it wont work. You need to run this command from the projects root directory (it has the README.md) in it)

**Comment by logicminds** [comment]
I had to add a config called theme = <theme directory name>

```
baseURL = ""
languageCode = "en-us"
title = "Hugo Hero"
themesDir = "themes"
theme = "hugohero"
```

```
├── resources
│   └── _gen
├── spell_check.sh
├── static
│   ├── favicon.png
│   ├── features
│   ├── services
│   └── work
└── themes
    └── hugohero
```

**Comment by JugglerX** [comment]
I have updated the documentation to (hopefully) make installing and configuring the config.toml clearer. I have also added `theme = "hugo-hero-theme"` to the example config.toml.
