### ISSUE TITLE
Error building site

### ISSUE THREAD

**Issue by ehrlichja** [JugglerX/hugo-hero-theme#8]
This is the same as issue #7 , here are the steps I followed (taken verbatim from the Readme):
$ hugo version
Hugo Static Site Generator v0.54.0/extended darwin/amd64 BuildDate: unknown
$ hugo new site mynewsite
Congratulations! Your new Hugo site is created in ...
$ cd mynewsite
$ cd themes
git clone https://github.com/jugglerx/hugo-hero-theme.git

config.toml reads:
```
baseURL = "/"
themesDir = "themes"
theme = "hugo-hero-theme"
```

$ hugo

```Error: Error building site: failed to render pages: render of "home" failed: "/Users/andrewehrlich/andrew/Companies/regulus/engineering/website/mynewsite/themes/hugo-hero-theme/layouts/index.html:23:30": execute of template failed: template: index.html:23:30: executing "main" at <$headless.Resources....>: can't evaluate field Resources in type *hugolib.Page```

**Comment by JugglerX** [comment]
Hi,

I just installed a fresh copy on my local and it worked.

After you do git clone https://github.com/jugglerx/hugo-hero-theme.git you need to copy the **contents* of the `exampleSite` folder from `/mynewsite/themes/hugo-hero-theme/exampleSite` -> `/mynewsite/`

You then edit the `/mynewsite/config.toml`

Then make sure you run `hugo` from the root director, ie `/mynewsite/

I'd say you have either not copied the `exampleSite` content correctly, or you are running `hugo` from the wrong folder.

**Comment by ehrlichja** [comment]
Thank you, it took a few more tries for me to get it. Appreciated.
